[project]
name = "rlcard-judgement"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pip>=26.0.1",
    "rlcard>=1.2.0",
]
